//CRUD PRODUCT IN CART
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const VIEW_PRODUCT = 'VIEW_PRODUCT';

//API
export const URL = "http://localhost:8080/capstone/";
export const UPDATE_PRODUCT_LINES = "UPDATE_PRODUCT_LINES";
export const UPDATE_PRODUCT_TYPES = "UPDATE_PRODUCT_TYPES"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const UPDATE_PRODUCT_PHOTOS = "UPDATE_PRODUCT_PHOTOS";
export const UPDATE_PRODUCT_DESCRIPTIONS = "UPDATE_PRODUCT_DESCRIPTIONS";

//LOGIN

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

//PRODUCTS 
export const FETCH_PRODUCTS_REQUESTED = "FETCH_PRODUCT_REQUESTED";
export const GET_PRODUCTS_SUCCEED = "GET_USER_SUCCEED";
export const GET_PRODUCTS_FAILED = "GET_USER_FAILED";

//PRODUCTLINES
export const FETCH_PRODUCT_LINES_REQUESTED = "FETCH_PRODUCT_REQUESTED";
export const GET_PRODUCT_LINES_SUCCEED = "GET_USER_SUCCEED";
export const GET_PRODUCT_LINES_FAILED = "GET_USER_FAILED";

//DEVICE
export const COMPUTER = "COMPUTER";
export const TABLET =  "TABLET";
export const MOBILE = "MOBILE";